<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanPhamSeeding extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('san_phams')->delete();
        // DB::table('san_phams')->truncate();
        DB::table('san_phams')->insert([
           [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Series 8 831 Mechanical NB6012-18L 40mm',
                'gia_ban' => 34485000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2023/11/01/resized/citizen-nb6012-18l-1_1698834496.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen nam Series 8 máy cơ, size 40mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Series 8 830 Mechanical NA1015-81Z 40mm',
                'gia_ban' => 55185000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2023/11/01/resized/citizen-na1015-81z-1_1698819981.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen nam Series 8 máy cơ, size 40mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Series 8 870 Mechanical NA1004-87E 40.8mm',
                'gia_ban' => 56885000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2023/11/01/resized/citizen-na1004-87e-4_1698815244.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen nam Series 8 máy cơ, size 40.8mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Series 8 GMT NB6030-59L',
                'gia_ban' => 47285000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2023/09/25/resized/dong-ho-citizen-series8-gmt-nb6030-59l-1-_1695626974.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen nam Series 8 GMT',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Movado Museum Classic 0607199 40mm',
                'gia_ban' => 21285000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2018/10/11/resized/dong-ho-movado-0607199-.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Movado nam Museum Classic, size 40mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Longines Automatic L4.960.4.92.6 38.5mm Nam',
                'gia_ban' => 40250000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2018/09/11/resized/dong-ho-longines-l4-960-4-92-6-.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Longines nam Automatic, size 38.5mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Bulova Marine Star Automatic 98A225 45mm',
                'gia_ban' => 14485000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2019/04/11/resized/bulova-98a225-.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Bulova nam Marine Star Automatic, size 45mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Movado Museum Classic 0607200 40mm',
                'gia_ban' => 26185000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2018/10/11/resized/dong-ho-movado-0607200-.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Movado nam Museum Classic, size 40mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Movado Bold Fusion Chronograph 3600894 44.5mm',
                'gia_ban' => 29785000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2022/11/11/resized/3600894_1668158845.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Movado nam Bold Fusion Chronograph, size 44.5mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Movado Museum Classic 0607202 40mm',
                'gia_ban' => 43085000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2021/11/12/resized/dong-ho-movado-0607202_1636691878.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Movado nam Museum Classic, size 40mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Setbox 2770213 40mm',
                'gia_ban' => 5685000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/09/13/resized/bulova-96a330-1_1757760148.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Setbox, size 40mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Oceanic 1792201 42mm',
                'gia_ban' => 3285000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-2770213-6_1755169498.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Oceanic, size 42mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Oceanic 1792200 42mm',
                'gia_ban' => 3285000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1792201-1_1755165981.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Oceanic, size 42mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Denim 1791483 44mm',
                'gia_ban' => 3885000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1792200-1_1755165834.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Denim, size 44mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Denim 1791381 42mm',
                'gia_ban' => 3885000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2023/11/01/resized/tommy-1791381-1.jpg',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Denim, size 42mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Denim 1791326 44mm',
                'gia_ban' => 3885000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1791483-1_1755165189.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Denim, size 44mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Bruce 1710677 43mm',
                'gia_ban' => 3885000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1791381-1_1755165042.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Bruce, size 43mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Bruce 1710670 43mm',
                'gia_ban' => 3885000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1791326-1_1755164782.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Bruce, size 43mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Tommy Hilfiger Griffin 1710458 43mm',
                'gia_ban' => 3885000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1710677-1_1755147539.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Tommy Hilfiger nam Griffin, size 43mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Zenshin Mechanical NK5020-58X 40.5mm',
                'gia_ban' => 26185000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1710670-1_1755147475.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Zenshin máy cơ, size 40.5mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Zenshin Mechanical NK5020-58P 40.5mm',
                'gia_ban' => 26185000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/14/resized/tommy-hilfiger-1710458-1_1755146548.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Zenshin máy cơ, size 40.5mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Zenshin Mechanical NK5020-58M 40.5mm',
                'gia_ban' => 26185000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/12/resized/citizen-nk5020-58x-1_1754993878.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Zenshin máy cơ, size 40.5mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Zenshin Mechanical NK5020-58L 40.5mm',
                'gia_ban' => 26185000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/12/resized/citizen-nk5020-58p-1_1754993057.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Zenshin máy cơ, size 40.5mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Satellite Wave GPS CC3031-51E 44mm',
                'gia_ban' => 31085000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/12/resized/citizen-nk5020-58m-1_1754992891.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Satellite Wave GPS, size 44mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen Satellite Wave GPS CC3030-53L 44mm',
                'gia_ban' => 31085000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/12/resized/citizen-nk5020-58l-1_1754992801.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Satellite Wave GPS, size 44mm',
                'is_noi_bat' => 1,
                'is_flash_sale' => 1
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen The Citizen Limited AQ4100-65W 38.3mm',
                'gia_ban' => 161585000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/11/resized/citizen-aq4100-65w-1_1754909035.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen The Citizen Limited, size 38.3mm',
                'is_noi_bat' => 1,
                'is_flash_sale' => 1
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen The Citizen Limited AQ4100-57M 38.3mm',
                'gia_ban' => 178485000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/11/resized/citizen-aq4100-57m-1_1754908657.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen The Citizen Limited, size 38.3mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 1
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen The Citizen Iconic Nature Limited AQ4106-18X 38.3mm',
                'gia_ban' => 148685000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/11/resized/citizen-aq4106-18x-1_1754905937.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Iconic Nature Limited, size 38.3mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 1
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen The Citizen Iconic Nature Limited AQ4100-65H 38.3mm',
                'gia_ban' => 180185000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/08/11/resized/citizen-aq4106-00w-1_1754887338.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Iconic Nature Limited, size 38.3mm',
                'is_noi_bat' => 0,
                'is_flash_sale' => 1
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen The Citizen Iconic Nature Limited AQ4106-00W 38.3mm',
                'gia_ban' => 167285000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/07/08/resized/longines-flagship-heritage-l4-815-4-62-2-1_1751973384.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Iconic Nature Limited, size 38.3mm',
                'is_noi_bat' => 1,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Citizen The Citizen Iconic Nature Limited AQ4100-22W 38.3mm',
                'gia_ban' => 148385000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/07/08/resized/longines-conquest-l3-720-4-92-6-1_1751973075.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Citizen Iconic Nature Limited, size 38.3mm',
                'is_noi_bat' => 1,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Nam Longines Flagship Heritage Moonphase L4.815.4.62.2 38.5mm',
                'gia_ban' => 97350000,
                'hinh_anh' => 'https://donghotantan.vn/images/products/2025/07/08/resized/longines-flagship-heritage-l4-815-4-62-2-1_1751973384.jpg.webp',
                'so_luong' => 10,
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Longines Flagship Heritage Moonphase, size 38.5mm',
                'is_noi_bat' => 1,
                'is_flash_sale' => 0
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Casio Nữ LTP-1303D-7AVDF',
                'so_luong' => 26,
                'hinh_anh' => 'https://image.donghohaitrieu.com/wp-content/uploads/2023/09/LTP-1303D-7AVDF.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Casio LTP-1303D-7AVDF là một mẫu đồng hồ nữ với thiết kế tinh tế. Mặt số có nền trắng, được trang trí bằng các vạch đơn giản và 3 kim chỉ giờ, tạo nên đẹp thanh lịch và trang nhã. Vỏ đồng hồ được làm bằng chất liệu thép không gỉ cao cấp, đảm bảo độ bền và độ bóng bền vững với thời gian.',
                'gia_ban' => 1356000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Seiko Nữ SUR785P1',
                'so_luong' => 11,
                'hinh_anh' => 'https://image.donghohaitrieu.com/wp-content/uploads/2023/09/SUR785P1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Seiko SUR785P1 là một mẫu đồng hồ thời trang dành cho nữ với mặt số tròn nhỏ nhắn. Vỏ và dây đeo được làm từ kim loại mạ bạc, tạo nên vẻ đẹp sang trọng. Kim chỉ và vạch số mỏng tinh tế nổi bật trên nền số màu đen, tạo ra một sự hấp dẫn quyến rũ.',
                'gia_ban' => 3690000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Seiko Nữ SUP304P1',
                'so_luong' => 28,
                'hinh_anh' => 'https://image.donghohaitrieu.com/wp-content/uploads/2023/09/SUP304P1-1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Seiko SUP304P1 là một chiếc đồng hồ nữ đẳng cấp với mặt số tròn nhỏ nhắn. Kim chỉ và các vạch số La Mã được phủ màu đen tạo điểm nhấn rất nổi bật trên nền số màu trắng trang nhã. Dây đeo bằng chất liệu da màu đen có vân giúp tạo nên một phong cách thanh lịch và quyến rũ cho phái nữ.',
                'gia_ban' => 3930000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Pierre Lannier Nữ NOVA 023L928',
                'so_luong' => 22,
                'hinh_anh' => 'https://cdn.pierrelannier.vn/2024/08/pierre-lannier-023L928.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ nữ Nova 023L928 Milanese bằng thép mạ vàng hồng được trang trí bằng đá pha lê, tạo nên một chiếc đồng hồ vừa nhỏ gọn lại vô cùng quyến rũ nhờ các chi tiết hoàn thiện. Khám phá tất cả những ưu điểm của mẫu đồng hồ này và để mình bị cuốn hút bởi nó!',
                'gia_ban' => 5170000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Pierre Lannier Nữ NOVA 014J938',
                'so_luong' => 18,
                'hinh_anh' => 'https://cdn.vuahanghieu.com/unsafe/0x500/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/03/dong-ho-nu-pierre-lannier-048k658-mau-bac-6400614ec2975-02032023154150.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Mê mẩn với bộ sưu tập Nova của Pierre Lannier: những chiếc đồng hồ đẹp và tinh tế, mang đến sự sang trọng cho mọi cổ tay. Chiếc đồng hồ nữ 014J938 thép không gỉ mạ vàng hồng là hoàn toàn hiện đại và tinh tế, với mặt số đen có hiệu ứng nắng.',
                'gia_ban' => 3670000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ định vị trẻ em Oaxis myFirst Fone R1S',
                'so_luong' => 14,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2022/07/18/image-removebg-preview-5_637937563970551957.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Sản phẩm đồng hồ định vị trẻ em Oaxis myFirst Fone R1S đi kèm với thiết kế trẻ trung cùng tính năng theo dõi nhịp tim và thúc đẩy trẻ em tập thể dục thường xuyên hơn. Đồng hồ được trang bị nhiều bộ nhớ hơn so với thế hệ tiền nhiệm, lưu trữ được nhiều nhạc hơn và xếp hạng chống thấm nước được cải thiện.',
                'gia_ban' => 2650000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ thông minh MyKID 4G LITE',
                'so_luong' => 19,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2023/08/31/mykid4glite-d.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ thông minh MyKid 4G LITE là mẫu đồng hồ dành cho trẻ em được phụ huynh ưa chuộng trong năm 2023 khi sở hữu nhiều tính năng hữu ích cho cả phụ huynh và con trẻ. Phụ huynh có thể quan sát và quản lý con nhanh chóng hơn với tính năng gọi video, nghe lén, chụp lén từ xa,...',
                'gia_ban' => 1390000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ trẻ em Huawei Watch Kids 4 Pro',
                'so_luong' => 14,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2022/05/13/aslan-1.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Hiện nay, đồng hồ thông minh cho trẻ em trở nên khá phổ biến. Và dòng đồng hồ Huawei Watch Kids 4 Pro là một trong số đó. Với thiết kế hiện đại, đẹp mắt, chắc chắn đây sẽ là món đồ được nhiều các em nhỏ yêu thích.',
                'gia_ban' => 3990000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ định vị trẻ em myALO K74',
                'so_luong' => 28,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2023/11/29/myalo-k74-1.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ định vị trẻ em myALO K74 là một thiết bị thông minh có thể giúp bố mẹ theo dõi và bảo vệ trẻ từ xa. Đây cũng là một công cụ thông minh với nhiều tính năng hữu ích đồng hành cùng trẻ học tập và giải trí hàng ngày.',
                'gia_ban' => 2490000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ trẻ em Goly K10',
                'so_luong' => 24,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/08/26/goly-k10-den-3.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ trẻ em Goly K10 sẽ là một lựa chọn đáng để cân nhắc nếu phụ huynh vẫn còn đang lăn tăn không biết mua thiết bị nào, khi việc trang bị cho con trẻ một thiết bị công nghệ bên mình, giúp ba mẹ có thể dễ dàng theo dõi từ xa, phòng trừ các trường hợp rủi ro là điều cần thiết.',
                'gia_ban' => 1190000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ trẻ em Masstel Super Hero 4G',
                'so_luong' => 18,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2021/01/27/masstel-super-hero-4g-xanh.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Mẫu đồng hồ định vị Masstel Super Hero 4G chính hãng đang là một trong những sự lựa chọn được nhiều bậc phụ huynh quan tâm. Với thiết kế thân thiện và hỗ trợ nhiều tính năng hữu ích, đây sẽ là người bạn đồng hành cùng con bạn mỗi ngày.',
                'gia_ban' => 1950000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Huawei Watch Fit 4',
                'so_luong' => 23,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/05/16/fit-4-blk-3.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ thông minh Huawei Watch Fit 4 là lựa chọn lý tưởng cho những ai tìm kiếm sự kết hợp giữa công nghệ hiện đại và thiết kế thời trang. Sở hữu màn hình AMOLED 1.82 inch với độ phân giải 480x408 pixel, thiết bị mang đến chất lượng hiển thị sắc nét và sống động.',
                'gia_ban' => 2730000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Huawei Watch Fit 4 Pro',
                'so_luong' => 30,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/05/16/fit-4-pro-blk-3.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ thông minh Huawei Watch Fit 4 Pro là lựa chọn lý tưởng cho những ai tìm kiếm sự kết hợp giữa công nghệ hiện đại và thiết kế thời trang. Hoạt động trên nền hệ điều hành HarmonyOS, Watch Fit 4 Pro đem lại trải nghiệm mượt mà, linh hoạt cùng khả năng tương thích cao.',
                'gia_ban' => 5380000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Garmin Approach S50',
                'so_luong' => 28,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/02/12/garmin-approach-s50-43mm-4.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Garmin Approach S50 - 43MM là một mẫu đồng hồ thông minh cao cấp, được thiết kế dành riêng cho những người yêu thích công nghệ và quan tâm đến việc chăm sóc sức khỏe.',
                'gia_ban' => 10990000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Apple Watch Series 10',
                'so_luong' => 20,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/09/11/series-10-tu-nhien-1.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Apple Watch Series 10 - GPS + Cellular, 42mm - Viền Titan Dây Thép là phiên bản mới nhất của dòng đồng hồ thông minh Apple, mang đến sự kết hợp hoàn hảo giữa công nghệ tiên tiến và thiết kế sang trọng.',
                'gia_ban' => 21290000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Samsung Galaxy Watch7 40mm LTE',
                'so_luong' => 26,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/07/10/watch7-40mm-xanh-2.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Samsung Galaxy Watch 7 là chiếc đồng hồ thế hệ mới nhất của Samsung Watch, mang đến sự kết hợp hoàn hảo giữa thiết kế thời trang, hiệu năng mạnh mẽ và các tính năng sức khỏe tiên tiến.',
                'gia_ban' => 8990000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Realme Band 2',
                'so_luong' => 27,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2021/10/20/realme-band-2-4.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Realme Band 2 chính hãng là đồng hồ thông minh thế hệ thứ 2 với những cải tiến từ thế hệ trước.',
                'gia_ban' => 460000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
        ]);
    }
}
