<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanPhamSeeding extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('san_phams')->delete();
        DB::table('san_phams')->truncate();
        DB::table('san_phams')->insert([
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Casio Nam MTP-1374L-1AVDF',
                'so_luong' => 18,
                'hinh_anh' => 'https://media.shopdongho.com/2021/05/hinh-anh-dong-ho-casio-mtp-1374l-1avdf-nam-pin-day-da-new-1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ nam Casio MTP-1374L-1AVDF được làm từ chất liệu cao cấp, với dây da thật màu đen được thiết kế vân nổi bật. Mặt đồng hồ có màu đen trang nhã, kết hợp với viền đen bao quanh và chữ số vạch lớn rõ nét. Ngoài ra, đồng hồ còn tích hợp chức năng lịch ngày, tiện lợi cho người sử dụng.',
                'gia_ban' => 2270000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Casio Nam AE-1200WHD-1AVDF',
                'so_luong' => 22,
                'hinh_anh' => 'https://media.shopdongho.com/2021/05/hinh-anh-AE-1200WHD-1AVDF-new-2.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ nam Casio AE-1200WHD-1AVDF sở hữu mặt vuông thể thao, màn hình điện tử sắc nét và dây đeo kim loại bền bỉ. Thiết kế mạnh mẽ, phù hợp cho nam giới năng động.',
                'gia_ban' => 1506000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Casio Nam MTP-VT01L-1BUDF',
                'so_luong' => 13,
                'hinh_anh' => 'https://media.shopdongho.com/2023/04/dong-ho-Casio-MTP-VT01L-1BUDF-1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ nam Casio MTP-VT01L-1BUDF với phần dây da tone đen tạo hình vân cá sấu, kết hợp với các chi tiết vỏ máy mạ bạc và kiểu thiết kế mỏng độ dày chỉ 8mm. Với thiết kế đơn giản nhưng đầy phong cách, mẫu đồng hồ này trở thành một lựa chọn tuyệt vời cho những quý ông yêu thích phong cách thanh lịch.',
                'gia_ban' => 1182000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Seiko Nam SNZG15K1',
                'so_luong' => 14,
                'hinh_anh' => 'https://media.shopdongho.com/2020/03/seiko-SNZG15K1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Mẫu Seiko SNZG15K1 là phiên bản thuộc dòng Seiko 5 với dây vải, kết hợp cùng phần vỏ máy cơ được thiết kế dày dặn và khả năng chống nước lên đến 10ATM. Kim chỉ và cọc vạch số được phủ dạ quang, giúp dễ dàng nhìn rõ trên mặt số của đồng hồ.',
                'gia_ban' => 6640000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Seiko Nam SSB205P1',
                'so_luong' => 17,
                'hinh_anh' => 'https://media.shopdongho.com/2019/09/seiko-SSB205P1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Seiko SSB205P1 dành cho nam có kiểu dáng thể thao và vỏ máy bằng thép không gỉ màu bạc sang trọng. Nó đi kèm với 3 ô phụ và chức năng Chronograph, đồng hồ nam tính này còn có dây đeo kim loại mang đến phong cách mạnh mẽ và nam tính.',
                'gia_ban' => 5510000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 1,
                'ten_san_pham' => 'Đồng Hồ Orient Nam RA-AR0003L10B',
                'so_luong' => 28,
                'hinh_anh' => 'https://media.shopdongho.com/2017/10/orient-RA-AR0003L10B.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Chiếc đồng hồ nam Orient RA-AR003L10B mang thiết kế thanh lịch, mặt số màu xanh độc đáo cùng chất lượng bền bỉ, chắc chắn sẽ khiến phái mạnh không khỏi ao ước được sở hữu.',
                'gia_ban' => 10400000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Casio Nữ LTP-V300L-1AUDF',
                'so_luong' => 30,
                'hinh_anh' => 'https://media.shopdongho.com/2024/05/MqKplko6-dong-ho-casio-ltp-v300l-1audf-nu-quartz-1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Casio LTP-V300L-1AUDF có thiết kế độc đáo với mặt số tròn lớn, được trang bị các chức năng hiển thị lịch riêng biệt tại vị trí 3 giờ, tạo nên kiểu dáng đồng hồ 6 kim thời trang và tiện ích cho người dùng.',
                'gia_ban' => 1752000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Casio Nữ LTP-1303D-7AVDF',
                'so_luong' => 26,
                'hinh_anh' => 'https://media.shopdongho.com/2018/09/casio-ltp-1303d-7avdf.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Casio LTP-1303D-7AVDF là một mẫu đồng hồ nữ với thiết kế tinh tế. Mặt số có nền trắng, được trang trí bằng các vạch đơn giản và 3 kim chỉ giờ, tạo nên đẹp thanh lịch và trang nhã. Vỏ đồng hồ được làm bằng chất liệu thép không gỉ cao cấp, đảm bảo độ bền và độ bóng bền vững với thời gian.',
                'gia_ban' => 1356000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Seiko Nữ SUR785P1',
                'so_luong' => 11,
                'hinh_anh' => 'https://media.shopdongho.com/2018/05/seiko-sur785p1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Seiko SUR785P1 là một mẫu đồng hồ thời trang dành cho nữ với mặt số tròn nhỏ nhắn. Vỏ và dây đeo được làm từ kim loại mạ bạc, tạo nên vẻ đẹp sang trọng. Kim chỉ và vạch số mỏng tinh tế nổi bật trên nền số màu đen, tạo ra một sự hấp dẫn quyến rũ.',
                'gia_ban' => 3690000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Seiko Nữ SUP304P1',
                'so_luong' => 28,
                'hinh_anh' => 'https://media.shopdongho.com/2019/09/seiko-SUP304P1.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ Seiko SUP304P1 là một chiếc đồng hồ nữ đẳng cấp với mặt số tròn nhỏ nhắn. Kim chỉ và các vạch số La Mã được phủ màu đen tạo điểm nhấn rất nổi bật trên nền số màu trắng trang nhã. Dây đeo bằng chất liệu da màu đen có vân giúp tạo nên một phong cách thanh lịch và quyến rũ cho phái nữ.',
                'gia_ban' => 3930000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Pierre Lannier Nữ NOVA 023L928',
                'so_luong' => 22,
                'hinh_anh' => 'https://media.shopdongho.com/2021/01/pierre-lannier-023L928.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ nữ Nova 023L928 Milanese bằng thép mạ vàng hồng được trang trí bằng đá pha lê, tạo nên một chiếc đồng hồ vừa nhỏ gọn lại vô cùng quyến rũ nhờ các chi tiết hoàn thiện. Khám phá tất cả những ưu điểm của mẫu đồng hồ này và để mình bị cuốn hút bởi nó!',
                'gia_ban' => 5170000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 2,
                'ten_san_pham' => 'Đồng Hồ Pierre Lannier Nữ NOVA 014J938',
                'so_luong' => 18,
                'hinh_anh' => 'https://media.shopdongho.com/2021/01/pierre-lannier-014J938.jpg',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Mê mẩn với bộ sưu tập Nova của Pierre Lannier: những chiếc đồng hồ đẹp và tinh tế, mang đến sự sang trọng cho mọi cổ tay. Chiếc đồng hồ nữ 014J938 thép không gỉ mạ vàng hồng là hoàn toàn hiện đại và tinh tế, với mặt số đen có hiệu ứng nắng.',
                'gia_ban' => 3670000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ định vị trẻ em Oaxis myFirst Fone R1S',
                'so_luong' => 14,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2022/07/18/image-removebg-preview-5_637937563970551957.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Sản phẩm đồng hồ định vị trẻ em Oaxis myFirst Fone R1S đi kèm với thiết kế trẻ trung cùng tính năng theo dõi nhịp tim và thúc đẩy trẻ em tập thể dục thường xuyên hơn. Đồng hồ được trang bị nhiều bộ nhớ hơn so với thế hệ tiền nhiệm, lưu trữ được nhiều nhạc hơn và xếp hạng chống thấm nước được cải thiện.',
                'gia_ban' => 2650000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ thông minh MyKID 4G LITE',
                'so_luong' => 19,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2023/08/31/mykid4glite-d.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ thông minh MyKid 4G LITE là mẫu đồng hồ dành cho trẻ em được phụ huynh ưa chuộng trong năm 2023 khi sở hữu nhiều tính năng hữu ích cho cả phụ huynh và con trẻ. Phụ huynh có thể quan sát và quản lý con nhanh chóng hơn với tính năng gọi video, nghe lén, chụp lén từ xa,...',
                'gia_ban' => 1390000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ trẻ em Huawei Watch Kids 4 Pro',
                'so_luong' => 14,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2022/05/13/aslan-1.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Hiện nay, đồng hồ thông minh cho trẻ em trở nên khá phổ biến. Và dòng đồng hồ Huawei Watch Kids 4 Pro là một trong số đó. Với thiết kế hiện đại, đẹp mắt, chắc chắn đây sẽ là món đồ được nhiều các em nhỏ yêu thích.',
                'gia_ban' => 3990000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ định vị trẻ em myALO K74',
                'so_luong' => 28,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2023/11/29/myalo-k74-1.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ định vị trẻ em myALO K74 là một thiết bị thông minh có thể giúp bố mẹ theo dõi và bảo vệ trẻ từ xa. Đây cũng là một công cụ thông minh với nhiều tính năng hữu ích đồng hành cùng trẻ học tập và giải trí hàng ngày.',
                'gia_ban' => 2490000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ trẻ em Goly K10',
                'so_luong' => 24,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/08/26/goly-k10-den-3.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ trẻ em Goly K10 sẽ là một lựa chọn đáng để cân nhắc nếu phụ huynh vẫn còn đang lăn tăn không biết mua thiết bị nào, khi việc trang bị cho con trẻ một thiết bị công nghệ bên mình, giúp ba mẹ có thể dễ dàng theo dõi từ xa, phòng trừ các trường hợp rủi ro là điều cần thiết.',
                'gia_ban' => 1190000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 3,
                'ten_san_pham' => 'Đồng hồ trẻ em Masstel Super Hero 4G',
                'so_luong' => 18,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2021/01/27/masstel-super-hero-4g-xanh.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Mẫu đồng hồ định vị Masstel Super Hero 4G chính hãng đang là một trong những sự lựa chọn được nhiều bậc phụ huynh quan tâm. Với thiết kế thân thiện và hỗ trợ nhiều tính năng hữu ích, đây sẽ là người bạn đồng hành cùng con bạn mỗi ngày.',
                'gia_ban' => 1950000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Huawei Watch Fit 4',
                'so_luong' => 23,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/05/16/fit-4-blk-3.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ thông minh Huawei Watch Fit 4 là lựa chọn lý tưởng cho những ai tìm kiếm sự kết hợp giữa công nghệ hiện đại và thiết kế thời trang. Sở hữu màn hình AMOLED 1.82 inch với độ phân giải 480x408 pixel, thiết bị mang đến chất lượng hiển thị sắc nét và sống động.',
                'gia_ban' => 2730000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Huawei Watch Fit 4 Pro',
                'so_luong' => 30,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/05/16/fit-4-pro-blk-3.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Đồng hồ thông minh Huawei Watch Fit 4 Pro là lựa chọn lý tưởng cho những ai tìm kiếm sự kết hợp giữa công nghệ hiện đại và thiết kế thời trang. Hoạt động trên nền hệ điều hành HarmonyOS, Watch Fit 4 Pro đem lại trải nghiệm mượt mà, linh hoạt cùng khả năng tương thích cao.',
                'gia_ban' => 5380000,
                'is_noi_bat' => 0,
                'is_flash_sale' => 1,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Garmin Approach S50',
                'so_luong' => 28,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/02/12/garmin-approach-s50-43mm-4.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Garmin Approach S50 - 43MM là một mẫu đồng hồ thông minh cao cấp, được thiết kế dành riêng cho những người yêu thích công nghệ và quan tâm đến việc chăm sóc sức khỏe.',
                'gia_ban' => 10990000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Apple Watch Series 10',
                'so_luong' => 20,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/09/11/series-10-tu-nhien-1.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Apple Watch Series 10 - GPS + Cellular, 42mm - Viền Titan Dây Thép là phiên bản mới nhất của dòng đồng hồ thông minh Apple, mang đến sự kết hợp hoàn hảo giữa công nghệ tiên tiến và thiết kế sang trọng.',
                'gia_ban' => 21290000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Samsung Galaxy Watch7 40mm LTE',
                'so_luong' => 26,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/07/10/watch7-40mm-xanh-2.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Samsung Galaxy Watch 7 là chiếc đồng hồ thế hệ mới nhất của Samsung Watch, mang đến sự kết hợp hoàn hảo giữa thiết kế thời trang, hiệu năng mạnh mẽ và các tính năng sức khỏe tiên tiến.',
                'gia_ban' => 8990000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
            [
                'id_danh_muc' => 4,
                'ten_san_pham' => 'Đồng hồ thông minh Realme Band 2',
                'so_luong' => 27,
                'hinh_anh' => 'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2021/10/20/realme-band-2-4.png',
                'tinh_trang' => 1,
                'mo_ta_ngan' => 'Realme Band 2 chính hãng là đồng hồ thông minh thế hệ thứ 2 với những cải tiến từ thế hệ trước.',
                'gia_ban' => 460000,
                'is_noi_bat' => 1,
                'is_flash_sale' => 0,
            ],
        ]);
    }
}
