<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanPhamSeeding extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('san_phams')->delete();
        DB::table('san_phams')->insert([
            $this->sanPham(
                1,
                'Đồng Hồ Casio Nam MTP-1374L-1AVDF',
                18,
                'https://cdn.tgdd.vn/Products/Images/7264/313967/casio-mtp-1374l-1avdf-nam-1-750x500.jpg',
                'Đồng hồ nam Casio MTP-1374L-1AVDF được làm từ chất liệu cao cấp, dây da thật màu đen, mặt số dễ nhìn, tích hợp lịch ngày.',
                2270000,
                0,
                1
            ),
            $this->sanPham(
                1,
                'Đồng Hồ Casio Nam AE-1200WHD-1AVDF',
                22,
                'https://cdn.tgdd.vn/Products/Images/7264/199485/casio-ae-1200whd-1avdf-bac-up-1-750x500.jpg',
                'Đồng hồ nam Casio AE-1200WHD-1AVDF sở hữu mặt vuông thể thao, màn hình điện tử sắc nét và dây đeo kim loại bền bỉ. Thiết kế mạnh mẽ, phù hợp cho nam giới năng động.',
                1506000,
                0,
                1,
            ),
            $this->sanPham(
                1,
                'Đồng Hồ Casio Nam MTP-VT01L-1BUDF',
                13,
                'https://image.donghohaitrieu.com/wp-content/uploads/2023/09/80_MTP-VT01L-1BUDF.jpg',
                'Đồng hồ nam Casio MTP-VT01L-1BUDF với phần dây da tone đen tạo hình vân cá sấu, kết hợp với các chi tiết vỏ máy mạ bạc và kiểu thiết kế mỏng độ dày chỉ 8mm. Với thiết kế đơn giản nhưng đầy phong cách, mẫu đồng hồ này trở thành một lựa chọn tuyệt vời cho những quý ông yêu thích phong cách thanh lịch.',
                1182000,
                1,
                0,
            ),
            $this->sanPham(
                1,
                'Đồng Hồ Seiko Nam SNZG15K1',
                14,
                'https://xwatch.vn/images/products/2020/04/28/large/dong-ho-seiko-snzg15k1-1_1588064606.jpg',
                'Mẫu Seiko SNZG15K1 là phiên bản thuộc dòng Seiko 5 với dây vải, kết hợp cùng phần vỏ máy cơ được thiết kế dày dặn và khả năng chống nước lên đến 10ATM. Kim chỉ và cọc vạch số được phủ dạ quang, giúp dễ dàng nhìn rõ trên mặt số của đồng hồ.',
                6640000,
                1,
                0,
            ),
            $this->sanPham(
                1,
                'Đồng Hồ Seiko Nam SSB205P1',
                17,
                'https://xshipimage.s3-ap-southeast-1.amazonaws.com/Seiko/SSB205P1/SSB205P1.jpg',
                'Đồng hồ Seiko SSB205P1 dành cho nam có kiểu dáng thể thao và vỏ máy bằng thép không gỉ màu bạc sang trọng. Nó đi kèm với 3 ô phụ và chức năng Chronograph, đồng hồ nam tính này còn có dây đeo kim loại mang đến phong cách mạnh mẽ và nam tính.',
                5510000,
                0,
                1,
            ),
            $this->sanPham(
                1,
                'Đồng Hồ Orient Nam RA-AR0003L10B',
                28,
                'https://cdn.tgdd.vn/Products/Images/7264/202689/orient-ra-ar0003l10b-nam-co-tu-dong-5-1-750x500.jpg',
                'Chiếc đồng hồ nam Orient RA-AR003L10B mang thiết kế thanh lịch, mặt số màu xanh độc đáo cùng chất lượng bền bỉ, chắc chắn sẽ khiến phái mạnh không khỏi ao ước được sở hữu.',
                10400000,
                0,
                1,
            ),
            $this->sanPham(
                1,
                'Đồng hồ Citizen Nam BI5124-50L',
                21,
                'https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7264/333114/citizen-bi5124-50l-nam-1-638702014050674289-750x500.jpg',
                'Đồng hồ Citizen 40 mm Nam BI5124-50L là mẫu đồng hồ nam được thiết kế với phong cách cổ điển và sang trọng, phù hợp để mang khi đi làm, đi chơi hoặc các buổi tiệc cần sự chỉn chu.',
                4585000,
                0,
                1,
            ),
            $this->sanPham(
                1,
                'Đồng hồ Orient Vietnam Special Edition Nam RA-AS0106L30B',
                21,
                'https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7264/332552/orient-ra-as0106l30b-nam-1-638684901280757694-750x500.jpg',
                'Đồng hồ Orient Vietnam Special Edition 41.5 mm Nam RA-AS0106L30B là một sản phẩm mang trong mình tinh thần tự hào dân tộc với thiết kế đậm chất cổ điển, sang trọng. Mẫu đồng hồ này được phát triển dựa trên dòng Classic Semi Skeleton - một trong những bộ sưu tập ăn khách nhất của Orient Star.',
                16000000,
                0,
                0,
            ),
            $this->sanPham(
                1,
                'Đồng hồ Orient Contemporary 40 mm Nam RA-TX0302S10B',
                21,
                'https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7264/331121/orient-ra-tx0302s10b-nam-1-638654688640004251-750x500.jpg',
                'Đồng hồ Orient Contemporary 40 mm Nam RA-TX0302S10B là một biểu tượng của sự tinh tế và hiện đại, mang đến phong cách lịch lãm cho những quý ông yêu thích sự sang trọng. Với thiết kế kết hợp giữa hai tông màu bạc và vàng kim, chiếc đồng hồ này không chỉ thể hiện sự đẳng cấp mà còn tạo điểm nhấn đầy cuốn hút trên cổ tay người đeo.',
                9400000,
                1,
                0,
            ),
            $this->sanPham(
                2,
                'Đồng Hồ Casio Nữ LTP-V300L-1AUDF',
                30,
                'https://cdn.tgdd.vn/Products/Images/7264/208631/casio-ltp-v300l-1audf-nu-2-750x500.jpg',
                'Đồng hồ Casio LTP-V300L-1AUDF có thiết kế độc đáo với mặt số tròn lớn, được trang bị các chức năng hiển thị lịch riêng biệt tại vị trí 3 giờ, tạo nên kiểu dáng đồng hồ 6 kim thời trang và tiện ích cho người dùng.',
                1752000,
                1,
                0,
            ),
            $this->sanPham(
                2,
                'Đồng Hồ Casio Nữ LTP-1303D-7AVDF',
                26,
                'https://image.donghohaitrieu.com/wp-content/uploads/2023/09/LTP-1303D-7AVDF.jpg',
                'Đồng hồ Casio LTP-1303D-7AVDF là một mẫu đồng hồ nữ với thiết kế tinh tế. Mặt số có nền trắng, được trang trí bằng các vạch đơn giản và 3 kim chỉ giờ, tạo nên đẹp thanh lịch và trang nhã. Vỏ đồng hồ được làm bằng chất liệu thép không gỉ cao cấp, đảm bảo độ bền và độ bóng bền vững với thời gian.',
                1356000,
                0,
                1,
            ),
            $this->sanPham(
                2,
                'Đồng Hồ Seiko Nữ SUR785P1',
                11,
                'https://image.donghohaitrieu.com/wp-content/uploads/2023/09/SUR785P1.jpg',
                'Seiko SUR785P1 là một mẫu đồng hồ thời trang dành cho nữ với mặt số tròn nhỏ nhắn. Vỏ và dây đeo được làm từ kim loại mạ bạc, tạo nên vẻ đẹp sang trọng. Kim chỉ và vạch số mỏng tinh tế nổi bật trên nền số màu đen, tạo ra một sự hấp dẫn quyến rũ.',
                3690000,
                1,
                0,
            ),
            $this->sanPham(
                2,
                'Đồng Hồ Seiko Nữ SUP304P1',
                28,
                'https://image.donghohaitrieu.com/wp-content/uploads/2023/09/SUP304P1-1.jpg',
                'Đồng hồ Seiko SUP304P1 là một chiếc đồng hồ nữ đẳng cấp với mặt số tròn nhỏ nhắn. Kim chỉ và các vạch số La Mã được phủ màu đen tạo điểm nhấn rất nổi bật trên nền số màu trắng trang nhã. Dây đeo bằng chất liệu da màu đen có vân giúp tạo nên một phong cách thanh lịch và quyến rũ cho phái nữ.',
                3930000,
                0,
                1,
            ),
            $this->sanPham(
                2,
                'Đồng Hồ Pierre Lannier Nữ NOVA 023L928',
                22,
                'https://cdn.pierrelannier.vn/2024/08/pierre-lannier-023L928.jpg',
                'Đồng hồ nữ Nova 023L928 Milanese bằng thép mạ vàng hồng được trang trí bằng đá pha lê, tạo nên một chiếc đồng hồ vừa nhỏ gọn lại vô cùng quyến rũ nhờ các chi tiết hoàn thiện. Khám phá tất cả những ưu điểm của mẫu đồng hồ này và để mình bị cuốn hút bởi nó!',
                5170000,
                1,
                0,
            ),
            $this->sanPham(
                2,
                'Đồng Hồ Pierre Lannier Nữ NOVA 014J938',
                18,
                'https://cdn.vuahanghieu.com/unsafe/0x500/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/03/dong-ho-nu-pierre-lannier-048k658-mau-bac-6400614ec2975-02032023154150.jpg',
                'Mê mẩn với bộ sưu tập Nova của Pierre Lannier: những chiếc đồng hồ đẹp và tinh tế, mang đến sự sang trọng cho mọi cổ tay. Chiếc đồng hồ nữ 014J938 thép không gỉ mạ vàng hồng là hoàn toàn hiện đại và tinh tế, với mặt số đen có hiệu ứng nắng.',
                3670000,
                0,
                1,
            ),
            $this->sanPham(
                2,
                'Đồng hồ Citizen L 32 mm Nữ EM0814-83A',
                20,
                'https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7264/330016/citizen-em0814-83a-nu-1-638629702702822863-750x500.jpg',
                'CITIZEN EM0814-83A - mẫu nữ xuất xứ từ Nhật Bản, sử dụng bộ máy Eco-Drive độc quyền của hãng Citizen, chuyển hóa mọi nguồn sáng thành năng lượng, không cần thay pin thường xuyên. Vỏ và dây được làm bằng thép không gỉ 316L dạng lưới cao cấp chắc chắn, bền bỉ.',
                8050000,
                0,
                0,
            ),
            $this->sanPham(
                2,
                'Đồng hồ Orient Vietnam Special Edition Nữ RA-AG0729S30B',
                17,
                'https://cdnv2.tgdd.vn/mwg-static/dmx/Products/Images/7264/332553/orient-ra-ag0729s30b-nu-1-638684902078341204-700x467.jpg',
                'Orient Vietnam Special Edition RA-AG0729S30B mang đến thiết kế đầy ý nghĩa với mặt số lộ cơ tinh tế tại vị trí 9 giờ. Điểm nhấn đặc biệt là con số 50 và ngôi sao vàng năm cánh ở mốc 3 giờ, biểu tượng kỷ niệm 50 năm ngày thống nhất đất nước.',
                12800000,
                1,
                0,
            ),
            $this->sanPham(
                3,
                'Đồng hồ định vị trẻ em Oaxis myFirst Fone R1S',
                14,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2022/07/18/image-removebg-preview-5_637937563970551957.png',
                'Sản phẩm đồng hồ định vị trẻ em Oaxis myFirst Fone R1S đi kèm với thiết kế trẻ trung cùng tính năng theo dõi nhịp tim và thúc đẩy trẻ em tập thể dục thường xuyên hơn. Đồng hồ được trang bị nhiều bộ nhớ hơn so với thế hệ tiền nhiệm, lưu trữ được nhiều nhạc hơn và xếp hạng chống thấm nước được cải thiện.',
                2650000,
                1,
                0,
            ),
            $this->sanPham(
                3,
                'Đồng hồ thông minh MyKID 4G LITE',
                19,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2023/08/31/mykid4glite-d.png',
                'Đồng hồ thông minh MyKid 4G LITE là mẫu đồng hồ dành cho trẻ em được phụ huynh ưa chuộng trong năm 2023 khi sở hữu nhiều tính năng hữu ích cho cả phụ huynh và con trẻ. Phụ huynh có thể quan sát và quản lý con nhanh chóng hơn với tính năng gọi video, nghe lén, chụp lén từ xa,...',
                1390000,
                0,
                1,
            ),
            $this->sanPham(
                3,
                'Đồng hồ trẻ em Huawei Watch Kids 4 Pro',
                14,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2022/05/13/aslan-1.png',
                'Hiện nay, đồng hồ thông minh cho trẻ em trở nên khá phổ biến. Và dòng đồng hồ Huawei Watch Kids 4 Pro là một trong số đó. Với thiết kế hiện đại, đẹp mắt, chắc chắn đây sẽ là món đồ được nhiều các em nhỏ yêu thích.',
                3990000,
                1,
                0,
            ),
            $this->sanPham(
                3,
                'Đồng hồ định vị trẻ em myALO K74',
                28,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2023/11/29/myalo-k74-1.png',
                'Đồng hồ định vị trẻ em myALO K74 là một thiết bị thông minh có thể giúp bố mẹ theo dõi và bảo vệ trẻ từ xa. Đây cũng là một công cụ thông minh với nhiều tính năng hữu ích đồng hành cùng trẻ học tập và giải trí hàng ngày.',
                2490000,
                0,
                1,
            ),
            $this->sanPham(
                3,
                'Đồng hồ trẻ em Goly K10',
                24,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/08/26/goly-k10-den-3.png',
                'Đồng hồ trẻ em Goly K10 sẽ là một lựa chọn đáng để cân nhắc nếu phụ huynh vẫn còn đang lăn tăn không biết mua thiết bị nào, khi việc trang bị cho con trẻ một thiết bị công nghệ bên mình, giúp ba mẹ có thể dễ dàng theo dõi từ xa, phòng trừ các trường hợp rủi ro là điều cần thiết.',
                1190000,
                1,
                0,
            ),
            $this->sanPham(
                3,
                'Đồng hồ trẻ em Masstel Super Hero 4G',
                18,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2021/01/27/masstel-super-hero-4g-xanh.png',
                'Mẫu đồng hồ định vị Masstel Super Hero 4G chính hãng đang là một trong những sự lựa chọn được nhiều bậc phụ huynh quan tâm. Với thiết kế thân thiện và hỗ trợ nhiều tính năng hữu ích, đây sẽ là người bạn đồng hành cùng con bạn mỗi ngày.',
                1950000,
                0,
                1,
            ),
            $this->sanPham(
                3,
                'Đồng hồ Smile Kid 42 mm Trẻ em SL127-01',
                18,
                'https://cdn.tgdd.vn/Products/Images/7264/296724/smile-kid-sl127-01-tre-em-1-750x500.jpg',
                'Đồng hồ Smile Kid 42 mm Trẻ em SL127-01 này đến từ Smile Kid uy tín của Việt Nam. Những sản phẩm của hãng luôn được thông qua quy trình sản xuất nghiêm ngặt, kiểm soát chất lượng chặt chẽ, do đó đây luôn là thương hiệu được nhiều bậc cha mẹ tin dùng khi lựa chọn sản phẩm đồng hồ cho con trẻ.',
                260000,
                0,
                1,
            ),
            $this->sanPham(
                3,
                'Đồng hồ Smile Kid 41 mm Trẻ em SL213-05',
                12,
                'https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7264/338469/smile-kid-sl213-05-tre-em-1-638840401836659617-750x500.jpg',
                'Đến từ thương hiệu Smile Kid của Việt Nam, chiếc đồng hồ Smile Kid SL213-05 là sự lựa chọn hoàn hảo dành cho các bé yêu thích phong cách ngọt ngào, đáng yêu. Thiết kế nổi bật với màu hồng chủ đạo kết hợp cùng họa tiết cầu vồng và đám mây, chiếc đồng hồ này không chỉ là một công cụ xem giờ mà còn là một món phụ kiện thời trang đầy màu sắc.',
                290000,
                0,
                1,
            ),
            $this->sanPham(
                4,
                'Đồng hồ thông minh Huawei Watch Fit 4',
                23,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/05/16/fit-4-blk-3.png',
                'Đồng hồ thông minh Huawei Watch Fit 4 là lựa chọn lý tưởng cho những ai tìm kiếm sự kết hợp giữa công nghệ hiện đại và thiết kế thời trang. Sở hữu màn hình AMOLED 1.82 inch với độ phân giải 480x408 pixel, thiết bị mang đến chất lượng hiển thị sắc nét và sống động.',
                2730000,
                1,
                0,
            ),
            $this->sanPham(
                4,
                'Đồng hồ thông minh Huawei Watch Fit 4 Pro',
                30,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/05/16/fit-4-pro-blk-3.png',
                'Đồng hồ thông minh Huawei Watch Fit 4 Pro là lựa chọn lý tưởng cho những ai tìm kiếm sự kết hợp giữa công nghệ hiện đại và thiết kế thời trang. Hoạt động trên nền hệ điều hành HarmonyOS, Watch Fit 4 Pro đem lại trải nghiệm mượt mà, linh hoạt cùng khả năng tương thích cao.',
                5380000,
                0,
                1,
            ),
            $this->sanPham(
                4,
                'Đồng hồ thông minh Garmin Approach S50',
                28,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2025/02/12/garmin-approach-s50-43mm-4.png',
                'Garmin Approach S50 - 43MM là một mẫu đồng hồ thông minh cao cấp, được thiết kế dành riêng cho những người yêu thích công nghệ và quan tâm đến việc chăm sóc sức khỏe.',
                10990000,
                1,
                0,
            ),
            $this->sanPham(
                4,
                'Apple Watch Series 10',
                20,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/09/11/series-10-tu-nhien-1.png',
                'Apple Watch Series 10 - GPS + Cellular, 42mm - Viền Titan Dây Thép là phiên bản mới nhất của dòng đồng hồ thông minh Apple, mang đến sự kết hợp hoàn hảo giữa công nghệ tiên tiến và thiết kế sang trọng.',
                21290000,
                1,
                0,
            ),
            $this->sanPham(
                4,
                'Samsung Galaxy Watch7 40mm LTE',
                26,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2024/07/10/watch7-40mm-xanh-2.png',
                'Samsung Galaxy Watch 7 là chiếc đồng hồ thế hệ mới nhất của Samsung Watch, mang đến sự kết hợp hoàn hảo giữa thiết kế thời trang, hiệu năng mạnh mẽ và các tính năng sức khỏe tiên tiến.',
                8990000,
                1,
                0,
            ),
            $this->sanPham(
                4,
                'Đồng hồ thông minh Realme Band 2',
                27,
                'https://cdn.hoanghamobile.vn/i/preview-h-V2/Uploads/2021/10/20/realme-band-2-4.png',
                'Realme Band 2 chính hãng là đồng hồ thông minh thế hệ thứ 2 với những cải tiến từ thế hệ trước.',
                460000,
                1,
                0,
            ),
            $this->sanPham(
                4,
                'Amazfit Active 42.3mm dây silicone',
                7,
                'https://cdn.tgdd.vn/Products/Images/7077/322267/amazfit-active-den-hc-2-750x500.jpg',
                'Đồng hồ thông minh Amazfit Active 42.3 mm là sự kết hợp hoàn hảo giữa phong cách thời thượng và công nghệ tiên tiến. Với thiết kế mỏng nhẹ, màn hình AMOLED sắc nét cùng nhiều tính năng theo dõi sức khỏe chuyên nghiệp.',
                2940000,
                0,
                0,
            ),
            $this->sanPham(
                4,
                'Oppo Watch X2 46mm dây cao su',
                12,
                'https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7077/339861/oppo-watch-x2-day-cao-su-den-1-638868897311019676-750x500.jpg',
                'Khám phá sự tiện lợi và thời trang trong một thiết bị duy nhất - OPPO Watch X2 46mm dây cao su. Được trang bị những công nghệ tiên tiến nhất hiện nay, chiếc đồng hồ này không chỉ đồng hành với lối sống hiện đại mà còn là một tuyên ngôn về phong cách cá nhân.',
                9500000,
                0,
                1,
            ),
            $this->sanPham(
                4,
                'Amazfit Balance 2 47.4mm dây silicone',
                5,
                'https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7077/341454/amazfit-balance-2-hc-1-638905036853823401-750x500.jpg',
                'Amazfit Balance 2 mang lại cảm giác mạnh mẽ, chắc chắn nhưng không kém phần hiện đại và tinh tế. Toàn bộ bề mặt được bao phủ bởi màn hình AMOLED 1.5 inch với độ phân giải 480 x 480 pixels, cho hình ảnh hiển thị sống động và chi tiết. ',
                7900000,
                0,
                1,
            ),
        ]);
    }
    private function sanPham($idDanhMuc, $ten, $soLuong, $hinhAnh, $moTa, $giaBan, $isNoiBat, $isFlashSale)
    {
        $phanTram = null;
        $giaKhuyenMai = null;

        if ($isFlashSale == 1) {
            $phanTram = random_int(10, 30);
            $giaKhuyenMai = $giaBan * (100 - $phanTram) / 100;
        }

        $startDate = Carbon::create(2025, 1, 1);
        $endDate   = Carbon::now();

        return [
            'id_danh_muc'       => $idDanhMuc,
            'ten_san_pham'      => $ten,
            'so_luong'          => $soLuong,
            'hinh_anh'          => $hinhAnh,
            'tinh_trang'        => 1,
            'mo_ta_ngan'        => $moTa,
            'gia_ban'           => $giaBan,
            'phan_tram'         => $phanTram,
            'gia_khuyen_mai'    => $giaKhuyenMai,
            'is_noi_bat'        => $isNoiBat,
            'is_flash_sale'     => $isFlashSale,
            'created_at'        => Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp)),
            'updated_at'        => Carbon::now(),
        ];
    }
}
